import { describe, expect, it } from 'vitest';

import {
  DEAL_LINE_ITEM_DATA_GOTOVNOSTI_PROIZVODSTVA_FIELD_UNIVERSAL_IDENTIFIER,
  DEAL_LINE_ITEM_FOTO_PROIZVODSTVA_FIELD_UNIVERSAL_IDENTIFIER,
  DEAL_LINE_ITEM_GOTOVO_PROIZVODSTVA_FIELD_UNIVERSAL_IDENTIFIER,
  DEAL_LINE_ITEM_KOMMENTARIY_DLYA_PROIZVODSTVA_FIELD_UNIVERSAL_IDENTIFIER,
  DEAL_LINE_ITEM_V_PROIZVODSTVO_FIELD_UNIVERSAL_IDENTIFIER,
  DEAL_LINE_ITEM_VREMYA_GOTOVNOSTI_PROIZVODSTVA_FIELD_UNIVERSAL_IDENTIFIER,
  DEAL_LINE_ITEM_VZATO_V_RABOTU_PROIZVODSTVA_FIELD_UNIVERSAL_IDENTIFIER,
} from 'src/constants/universal-identifiers';

describe('production field identifiers', () => {
  it('uses the spec UUID v4 values', () => {
    expect(DEAL_LINE_ITEM_V_PROIZVODSTVO_FIELD_UNIVERSAL_IDENTIFIER).toBe(
      '7fc83b4d-a882-41c5-b7a9-df3b1e87fe4e',
    );
    expect(DEAL_LINE_ITEM_VZATO_V_RABOTU_PROIZVODSTVA_FIELD_UNIVERSAL_IDENTIFIER).toBe(
      '2dc2890a-853b-4160-b7a5-cc3a0c276a6b',
    );
    expect(DEAL_LINE_ITEM_GOTOVO_PROIZVODSTVA_FIELD_UNIVERSAL_IDENTIFIER).toBe(
      '5b0e9ae2-8c49-4cfe-8efe-eb969f48af25',
    );
    expect(DEAL_LINE_ITEM_DATA_GOTOVNOSTI_PROIZVODSTVA_FIELD_UNIVERSAL_IDENTIFIER).toBe(
      'd90b1112-da27-4511-b1a4-be793b069409',
    );
    expect(DEAL_LINE_ITEM_VREMYA_GOTOVNOSTI_PROIZVODSTVA_FIELD_UNIVERSAL_IDENTIFIER).toBe(
      '1eba76da-d1f8-4e51-a04e-9c5eb38fe8b1',
    );
    expect(DEAL_LINE_ITEM_KOMMENTARIY_DLYA_PROIZVODSTVA_FIELD_UNIVERSAL_IDENTIFIER).toBe(
      '414d1d12-133e-4f9f-a29f-70f5ed41587f',
    );
    expect(DEAL_LINE_ITEM_FOTO_PROIZVODSTVA_FIELD_UNIVERSAL_IDENTIFIER).toBe(
      '18d33025-b817-42b4-a63f-2713a18d5eea',
    );
  });
});
