import { defineObject, FieldType } from 'twenty-sdk/define';
import { TELEGRAM_REQUEST_KIND, TELEGRAM_REQUEST_STAGE } from 'src/constants/telegram-request';
import {
  TELEGRAM_REQUEST_BOOKING_FIELD_UNIVERSAL_IDENTIFIER,
  TELEGRAM_REQUEST_BRIEF_FIELD_UNIVERSAL_IDENTIFIER,
  TELEGRAM_REQUEST_COMPANY_FIELD_UNIVERSAL_IDENTIFIER,
  TELEGRAM_REQUEST_KIND_FIELD_UNIVERSAL_IDENTIFIER,
  TELEGRAM_REQUEST_LARGE_FILE_URLS_FIELD_UNIVERSAL_IDENTIFIER,
  TELEGRAM_REQUEST_LAYOUTS_URL_FIELD_UNIVERSAL_IDENTIFIER,
  TELEGRAM_REQUEST_LOGO_OR_BRAND_URL_FIELD_UNIVERSAL_IDENTIFIER,
  TELEGRAM_REQUEST_NOTIFY_ON_REPUBLISH_FIELD_UNIVERSAL_IDENTIFIER,
  TELEGRAM_REQUEST_OBJECT_UNIVERSAL_IDENTIFIER,
  TELEGRAM_REQUEST_POSITION_NAME_FIELD_UNIVERSAL_IDENTIFIER,
  TELEGRAM_REQUEST_PUBLISH_ERROR_FIELD_UNIVERSAL_IDENTIFIER,
  TELEGRAM_REQUEST_REPLY_TEXT_FIELD_UNIVERSAL_IDENTIFIER,
  TELEGRAM_REQUEST_REPUBLISH_REQUESTED_FIELD_UNIVERSAL_IDENTIFIER,
  TELEGRAM_REQUEST_REQUESTER_NAME_FIELD_UNIVERSAL_IDENTIFIER,
  TELEGRAM_REQUEST_REQUESTER_USERNAME_FIELD_UNIVERSAL_IDENTIFIER,
  TELEGRAM_REQUEST_REQUEST_FILES_FIELD_UNIVERSAL_IDENTIFIER,
  TELEGRAM_REQUEST_REQUEST_NUMBER_FIELD_UNIVERSAL_IDENTIFIER,
  TELEGRAM_REQUEST_REVIEW_ACTION_FIELD_UNIVERSAL_IDENTIFIER,
  TELEGRAM_REQUEST_STAGE_FIELD_UNIVERSAL_IDENTIFIER,
  TELEGRAM_REQUEST_TELEGRAM_MESSAGE_URL_FIELD_UNIVERSAL_IDENTIFIER,
} from 'src/constants/universal-identifiers';

export default defineObject({
  universalIdentifier: TELEGRAM_REQUEST_OBJECT_UNIVERSAL_IDENTIFIER,
  nameSingular: 'telegramRequest',
  namePlural: 'telegramRequests',
  labelSingular: 'Заявка бота',
  labelPlural: 'Заявки бота',
  icon: 'IconRobot',
  description: 'Заявки из Telegram-бота',
  fields: [
    {
      universalIdentifier: TELEGRAM_REQUEST_REQUEST_NUMBER_FIELD_UNIVERSAL_IDENTIFIER,
      name: 'requestNumber',
      type: FieldType.NUMBER,
      label: 'Номер заявки',
      icon: 'IconHash',
    },
    {
      universalIdentifier: TELEGRAM_REQUEST_STAGE_FIELD_UNIVERSAL_IDENTIFIER,
      name: 'stage',
      type: FieldType.SELECT,
      label: 'Статус',
      icon: 'IconProgress',
      defaultValue: `'${TELEGRAM_REQUEST_STAGE.NEW}'`,
      options: [
        { value: TELEGRAM_REQUEST_STAGE.NEW, label: 'Новый', position: 0, color: 'blue' },
        {
          value: TELEGRAM_REQUEST_STAGE.IN_PROGRESS,
          label: 'В работе',
          position: 1,
          color: 'orange',
        },
        { value: TELEGRAM_REQUEST_STAGE.DONE, label: 'Готовый', position: 2, color: 'green' },
      ],
    },
    {
      universalIdentifier: TELEGRAM_REQUEST_KIND_FIELD_UNIVERSAL_IDENTIFIER,
      name: 'kind',
      type: FieldType.SELECT,
      label: 'Тип заявки',
      icon: 'IconCategory',
      options: [
        { value: TELEGRAM_REQUEST_KIND.QUOTE, label: 'Просчёт', position: 0, color: 'blue' },
        { value: TELEGRAM_REQUEST_KIND.LAYOUT, label: 'Макет', position: 1, color: 'purple' },
        {
          value: TELEGRAM_REQUEST_KIND.VISUAL,
          label: 'Визуализация',
          position: 2,
          color: 'orange',
        },
        {
          value: TELEGRAM_REQUEST_KIND.REVIEW,
          label: 'Проверка',
          position: 3,
          color: 'yellow',
        },
      ],
    },
    {
      universalIdentifier: TELEGRAM_REQUEST_COMPANY_FIELD_UNIVERSAL_IDENTIFIER,
      name: 'company',
      type: FieldType.TEXT,
      label: 'Компания',
      icon: 'IconBuilding',
    },
    {
      universalIdentifier: TELEGRAM_REQUEST_REPLY_TEXT_FIELD_UNIVERSAL_IDENTIFIER,
      name: 'replyText',
      type: FieldType.TEXT,
      label: 'Ответ в чат',
      icon: 'IconMessageReply',
    },
    {
      universalIdentifier: TELEGRAM_REQUEST_REQUESTER_NAME_FIELD_UNIVERSAL_IDENTIFIER,
      name: 'requesterName',
      type: FieldType.TEXT,
      label: 'Имя заказчика',
      icon: 'IconUser',
    },
    {
      universalIdentifier: TELEGRAM_REQUEST_REQUESTER_USERNAME_FIELD_UNIVERSAL_IDENTIFIER,
      name: 'requesterUsername',
      type: FieldType.TEXT,
      label: 'Telegram username',
      icon: 'IconAt',
    },
    {
      universalIdentifier: TELEGRAM_REQUEST_TELEGRAM_MESSAGE_URL_FIELD_UNIVERSAL_IDENTIFIER,
      name: 'telegramMessageUrl',
      type: FieldType.TEXT,
      label: 'Сообщение в Telegram',
      icon: 'IconBrandTelegram',
    },
    {
      universalIdentifier: TELEGRAM_REQUEST_BRIEF_FIELD_UNIVERSAL_IDENTIFIER,
      name: 'brief',
      type: FieldType.TEXT,
      label: 'Бриф',
      icon: 'IconNotes',
    },
    {
      universalIdentifier: TELEGRAM_REQUEST_BOOKING_FIELD_UNIVERSAL_IDENTIFIER,
      name: 'booking',
      type: FieldType.TEXT,
      label: 'Бронь',
      icon: 'IconCalendar',
    },
    {
      universalIdentifier: TELEGRAM_REQUEST_POSITION_NAME_FIELD_UNIVERSAL_IDENTIFIER,
      name: 'positionName',
      type: FieldType.TEXT,
      label: 'Наименование позиции',
      icon: 'IconBox',
    },
    {
      universalIdentifier: TELEGRAM_REQUEST_LOGO_OR_BRAND_URL_FIELD_UNIVERSAL_IDENTIFIER,
      name: 'logoOrBrandUrl',
      type: FieldType.TEXT,
      label: 'Логотип или брендбук',
      icon: 'IconLink',
    },
    {
      universalIdentifier: TELEGRAM_REQUEST_LAYOUTS_URL_FIELD_UNIVERSAL_IDENTIFIER,
      name: 'layoutsUrl',
      type: FieldType.TEXT,
      label: 'Ссылка на макеты',
      icon: 'IconLink',
    },
    {
      universalIdentifier: TELEGRAM_REQUEST_REVIEW_ACTION_FIELD_UNIVERSAL_IDENTIFIER,
      name: 'reviewAction',
      type: FieldType.SELECT,
      label: 'Действие проверки',
      icon: 'IconChecklist',
      isNullable: true,
      options: [
        { value: 'CHECK', label: 'проверить', position: 0, color: 'yellow' },
        { value: 'LAUNCH', label: 'запускаем', position: 1, color: 'green' },
      ],
    },
    {
      universalIdentifier: TELEGRAM_REQUEST_LARGE_FILE_URLS_FIELD_UNIVERSAL_IDENTIFIER,
      name: 'largeFileUrls',
      type: FieldType.TEXT,
      label: 'Ссылки на большие файлы',
      icon: 'IconLink',
    },
    {
      universalIdentifier: TELEGRAM_REQUEST_NOTIFY_ON_REPUBLISH_FIELD_UNIVERSAL_IDENTIFIER,
      name: 'notifyOnRepublish',
      type: FieldType.BOOLEAN,
      label: 'Уведомить менеджера',
      icon: 'IconBell',
      defaultValue: false,
    },
    {
      universalIdentifier: TELEGRAM_REQUEST_REPUBLISH_REQUESTED_FIELD_UNIVERSAL_IDENTIFIER,
      name: 'republishRequested',
      type: FieldType.BOOLEAN,
      label: 'Обновить в Telegram',
      icon: 'IconRefresh',
      defaultValue: false,
    },
    {
      universalIdentifier: TELEGRAM_REQUEST_PUBLISH_ERROR_FIELD_UNIVERSAL_IDENTIFIER,
      name: 'publishError',
      type: FieldType.TEXT,
      label: 'Ошибка публикации',
      icon: 'IconAlertTriangle',
    },
    {
      universalIdentifier: TELEGRAM_REQUEST_REQUEST_FILES_FIELD_UNIVERSAL_IDENTIFIER,
      name: 'requestFiles',
      type: FieldType.FILES,
      label: 'Файлы заявки',
      icon: 'IconPaperclip',
      universalSettings: {
        maxNumberOfValues: 20,
      },
    },
  ],
});
